# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42cb2d6404d894de61e13271c1469ce6d413b3c78fa59b9425ae527b4dfcf1558c074baeec52e0d3a4d5fe12b18db4bcfb9bf01243aca0b43bc3a734067ccca5

test:
  secret_key_base: 38d27e6ac952c9e682bc46a4da8605659ad4c626d0d297a6669f6484125313d6ae7c32cbddb1ee7ff78cc40e76236708f2c2607937c66ed01a058dacf44a5d49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
